# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1598a5a2e8fb9f6a30723cda063ea7c2053e50ff33b9869d2e242e0ef8ff1e1e852e91a5911d0d953021e644f2ad01209cfc5aff228af7ca550034dfd9106f30

test:
  secret_key_base: 5bb2e8323f777bce58164224eb23716ecdfa174619b45c28007cb3cb3b6c4579aff5f1262aa12756bd482cc3ec44f38919f077cacf32731b9e4738002f40a9d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
